apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/uploads
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
