apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: opaque
data:
    POSTGRES_USER: cG9zdGdyZXM=
    POSTGRES_PASSWORD: MjAwMTAyMDk=
    POSTGRES_DB: d29ya291dA==
    DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOjIwMDEwMjA5QHBvc3RncmVzLWRiOjU0MzIvd29ya291dA==
