apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: opaque
data:
    POSTGRES_USER: #enter your postgres user
    POSTGRES_PASSWORD: #enter your postgres password
    POSTGRES_DB: #enter your database name
    DATABASE_URL: #enter your database url
