apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: image-storage
