apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-storage-claim
  namespace: workout-app-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: image-storage
