apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-postgres-statefulset-0
  namespace: workout-app-ns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeName: postgres-pv