apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: workout-app-ns
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/postgres/exercise_data
    type: DirectoryOrCreate
