apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: mihirajakuruppu123/workout-app-new
          ports:
            -  containerPort: 5000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
          volumeMounts:
            - name: image-storage
              mountPath: /app/static/uploads
      volumes:
      - name: image-storage
        persistentVolumeClaim:
          claimName: image-storage-claim
