apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: workout-app-ns
spec:
  selector:
    app: web-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
  type: NodePort
